<?php

return [
    'site_url' => env('SEO_SITE_URL', 'https://ldccourier.co.uk'),
    'site_name' => 'Transport & Courier Services',
    'locale' => 'en_US',
    'twitter_card' => 'summary_large_image',
    'default_image' => '/assets/images/2026/04/WhatsApp-Image-2026-03-02-at-10.51.48-PM-1.webp',
    'default_image_width' => 1351,
    'default_image_height' => 901,
    'logo' => '/assets/images/2026/03/logo_black-1.webp',
    'cookieyes_id' => env('COOKIEYES_ID', 'c1dd911159ee031a74d5bd960a15d15a'),
    'ga4_id' => env('GA4_MEASUREMENT_ID', 'G-4J1CTDVRE0'),
    'organization' => [
        'name' => 'Transport & Courier Services LDC Express Courier LTD',
        'description' => 'Transport & Courier Services Same day courier services in Kidderminster and across the UK. We provide fast and reliable transport for pallets, carpets and dedicated van deliveries.',
        'telephone' => '+447763734549',
    ],
    'pages' => [
        'home' => [
            'path' => '/',
            'title' => 'HOME - Transport & Courier Services',
            'description' => 'Same day courier in Kidderminster and across the UK. Fast delivery including pallets, carpets and dedicated vans. Get an instant quote today.',
            'breadcrumb' => 'Home',
            'priority' => '1.0',
            'changefreq' => 'weekly',
        ],
        'about-us-2' => [
            'path' => '/about-us-2',
            'title' => 'About Us - Transport & Courier Services',
            'description' => 'Same day courier in Kidderminster and across the UK. Fast, reliable delivery including pallets, vans and 7.5t trucks. Get an instant quote today.',
            'breadcrumb' => 'About Us',
            'priority' => '0.8',
            'changefreq' => 'monthly',
        ],
        'our-services' => [
            'path' => '/our-services',
            'title' => 'Our Services - Transport & Courier Services',
            'description' => 'Same-day courier, next-day delivery, pallet transport, carpet and flooring transport, and dedicated van services across Kidderminster and the UK. Fast collection and reliable delivery.',
            'breadcrumb' => 'Our Services',
            'priority' => '0.9',
            'changefreq' => 'weekly',
            'schema_type' => 'Service',
        ],
        'contact-us' => [
            'path' => '/contact-us',
            'title' => 'Contact Us - Transport & Courier Services',
            'description' => 'Contact LDC Courier for fast courier prices and same-day delivery support across Kidderminster and the UK. Receive your delivery price quickly and hassle-free.',
            'breadcrumb' => 'Contact Us',
            'priority' => '0.8',
            'changefreq' => 'monthly',
        ],
        'carpet-flooring-transport' => [
            'path' => '/carpet-flooring-transport',
            'title' => 'Carpet & Flooring Transport - Transport & Courier Services',
            'description' => 'Professional carpet and flooring transport across the UK for retailers, fitters and suppliers. Reliable Luton van, tail lift and 7.5T transport for flooring materials.',
            'breadcrumb' => 'Carpet & Flooring Transport',
            'priority' => '0.8',
            'changefreq' => 'monthly',
            'schema_type' => 'Service',
        ],
        'privacy-policy-2' => [
            'path' => '/privacy-policy-2',
            'title' => 'Privacy Policy | LDC Courier',
            'description' => 'Read the LDC Courier privacy policy, including how personal information is collected, used and protected.',
            'breadcrumb' => 'Privacy Policy',
            'priority' => '0.3',
            'changefreq' => 'yearly',
        ],
        'terms-conditions' => [
            'path' => '/terms-conditions',
            'title' => 'Terms & Conditions | LDC Courier',
            'description' => 'Read the LDC Courier terms and conditions for transport, courier bookings and website use.',
            'breadcrumb' => 'Terms & Conditions',
            'priority' => '0.3',
            'changefreq' => 'yearly',
        ],
        'cookie-policy' => [
            'path' => '/cookie-policy',
            'title' => 'Cookie Policy | LDC Courier',
            'description' => 'Read the LDC Courier cookie policy and learn how cookies are used for website functionality, analytics and user experience.',
            'breadcrumb' => 'Cookie Policy',
            'priority' => '0.3',
            'changefreq' => 'yearly',
        ],
        'blog' => [
            'path' => '/blog',
            'title' => 'Blog | LDC Courier',
            'description' => 'Latest news, service updates and transport guidance from LDC Courier.',
            'breadcrumb' => 'Blog',
            'priority' => '0.5',
            'changefreq' => 'monthly',
        ],
    ],
];
