<?php

return [
    'site_url' => env('SEO_SITE_URL', 'https://ldccourier.co.uk'),
    'site_name' => 'LDC Courier',
    'locale' => 'en_US',
    'twitter_card' => 'summary_large_image',
    'default_image' => '/assets/images/2026/04/WhatsApp-Image-2026-03-02-at-10.51.48-PM-1.webp',
    'default_image_width' => 1351,
    'default_image_height' => 901,
    'logo' => '/assets/images/2026/03/logo_black-1.webp',
    'cookieyes_id' => env('COOKIEYES_ID', 'c1dd911159ee031a74d5bd960a15d15a'),
    'ga4_id' => env('GA4_MEASUREMENT_ID', 'G-4J1CTDVRE0'),
    'organization' => [
        'name' => 'LDC Express Courier LTD',
        'description' => 'Same day courier services in Kidderminster, Worcester and Birmingham. LDC Courier provides fast pallet delivery, carpet transport, dedicated van courier, Luton van delivery and 7.5T tail lift courier services across the UK.',
        'telephone' => '+447763734549',
        'email' => 'orders@ldccourier.co.uk',
        'address' => [
            'addressLocality' => 'Kidderminster',
            'addressRegion' => 'Worcestershire',
            'addressCountry' => 'GB',
        ],
    ],
    'pages' => [
        'home' => [
            'path' => '/',
            'title' => 'Same Day Courier Kidderminster | LDC Courier',
            'description' => 'Same day courier in Kidderminster with fast collections for Worcester, Birmingham and UK deliveries. Book dedicated vans, pallets and Luton van transport.',
            'breadcrumb' => 'Home',
            'priority' => '1.0',
            'changefreq' => 'weekly',
            'schema_type' => 'LocalBusiness',
            'services' => [
                'Same Day Courier Kidderminster',
                'Pallet Delivery Kidderminster',
                'Dedicated Van Courier',
                'Luton Van Delivery',
            ],
        ],
        'about-us-2' => [
            'path' => '/about-us-2',
            'title' => 'About LDC Courier | Kidderminster Courier Service',
            'description' => 'Learn about LDC Courier, a Kidderminster transport company providing dedicated van courier, pallet delivery and 7.5T tail lift courier support across the UK.',
            'breadcrumb' => 'About Us',
            'priority' => '0.8',
            'changefreq' => 'monthly',
            'services' => [
                'Dedicated Van Courier',
                '7.5T Tail Lift Courier',
            ],
        ],
        'our-services' => [
            'path' => '/our-services',
            'title' => 'Same Day Courier Worcester & Birmingham | LDC Courier',
            'description' => 'Same day courier for Worcester and Birmingham from our Kidderminster base, including pallet delivery, dedicated van courier and 7.5T tail lift courier options.',
            'breadcrumb' => 'Our Services',
            'priority' => '0.9',
            'changefreq' => 'weekly',
            'schema_type' => 'Service',
            'services' => [
                'Same Day Courier Worcester',
                'Same Day Courier Birmingham',
                'Pallet Delivery Kidderminster',
                'Dedicated Van Courier',
                '7.5T Tail Lift Courier',
            ],
        ],
        'contact-us' => [
            'path' => '/contact-us',
            'title' => 'Contact Same Day Courier Kidderminster | LDC Courier',
            'description' => 'Contact LDC Courier for same day courier prices in Kidderminster, Worcester and Birmingham. Get a quick quote for pallets, carpets or dedicated van transport.',
            'breadcrumb' => 'Contact Us',
            'priority' => '0.8',
            'changefreq' => 'monthly',
            'services' => [
                'Same Day Courier Kidderminster',
                'Same Day Courier Worcester',
                'Same Day Courier Birmingham',
            ],
        ],
        'carpet-flooring-transport' => [
            'path' => '/carpet-flooring-transport',
            'title' => 'Carpet Transport Kidderminster & Birmingham | LDC Courier',
            'description' => 'Carpet transport from Kidderminster to Birmingham, Worcester and across the UK. Reliable flooring transport with Luton vans, tail lifts and 7.5T curtain-side trucks.',
            'breadcrumb' => 'Carpet & Flooring Transport',
            'priority' => '0.8',
            'changefreq' => 'monthly',
            'schema_type' => 'Service',
            'services' => [
                'Carpet Transport Kidderminster',
                'Carpet Transport Birmingham',
                'Luton Van Delivery',
                '7.5T Tail Lift Courier',
            ],
        ],
        'privacy-policy-2' => [
            'path' => '/privacy-policy-2',
            'title' => 'Privacy Policy | LDC Courier',
            'description' => 'Read the LDC Courier privacy policy, including how personal information is collected, used and protected.',
            'breadcrumb' => 'Privacy Policy',
            'priority' => '0.3',
            'changefreq' => 'yearly',
        ],
        'terms-conditions' => [
            'path' => '/terms-conditions',
            'title' => 'Terms & Conditions | LDC Courier',
            'description' => 'Read the LDC Courier terms and conditions for transport, courier bookings and website use.',
            'breadcrumb' => 'Terms & Conditions',
            'priority' => '0.3',
            'changefreq' => 'yearly',
        ],
        'cookie-policy' => [
            'path' => '/cookie-policy',
            'title' => 'Cookie Policy | LDC Courier',
            'description' => 'Read the LDC Courier cookie policy and learn how cookies are used for website functionality, analytics and user experience.',
            'breadcrumb' => 'Cookie Policy',
            'priority' => '0.3',
            'changefreq' => 'yearly',
        ],
    ],
];
